/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('./components/ActionButton.vue')['default']
    ActionRange: typeof import('./components/ActionRange.vue')['default']
    Actions: typeof import('./components/Actions.vue')['default']
    Alert: typeof import('./components/Alert.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    Chat: typeof import('./components/Chat.vue')['default']
    InputRangeWithNumber: typeof import('./components/InputRangeWithNumber.vue')['default']
    InputText: typeof import('./components/InputText.vue')['default']
    Player: typeof import('./components/Player.vue')['default']
    Room: typeof import('./components/Room.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpeedDial: typeof import("./components/SpeedDial.vue")["default"]
    Table: typeof import('./components/Table.vue')['default']
    Tool: typeof import('./components/Tool.vue')['default']
    Traits: typeof import('./components/Traits.vue')['default']
  }
}
